import type { Customer, Vehicle, JobCard, Bill, DashboardStats, InventoryItem, ServiceItem, PartItem, Notification } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Rajesh Kumar',
    email: 'rajesh@email.com',
    phone: '+91 98765 43210',
    address: '42 MG Road, Bengaluru',
    vehicles: [],
    createdAt: '2025-12-15T10:30:00Z',
  },
  {
    id: 'cust-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91 87654 32109',
    address: '15 Connaught Place, New Delhi',
    vehicles: [],
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'Amit Patel',
    email: 'amit.p@email.com',
    phone: '+91 76543 21098',
    address: '7 Satellite Road, Ahmedabad',
    vehicles: [],
    createdAt: '2026-02-20T14:15:00Z',
  },
  {
    id: 'cust-4',
    name: 'Sneha Reddy',
    email: 'sneha.r@email.com',
    phone: '+91 65432 10987',
    address: '23 Banjara Hills, Hyderabad',
    vehicles: [],
    createdAt: '2026-03-05T11:45:00Z',
  },
  {
    id: 'cust-5',
    name: 'Vikram Singh',
    email: 'vikram.s@email.com',
    phone: '+91 54321 09876',
    address: '8 Civil Lines, Jaipur',
    vehicles: [],
    createdAt: '2026-03-18T16:00:00Z',
  },
];

export const mockVehicles: Vehicle[] = [
  { id: 'veh-1', customerId: 'cust-1', make: 'BMW', model: '3 Series', year: 2023, color: 'Alpine White', licensePlate: 'KA-01-AB-1234', vin: 'WBA8E9G50JNU12345', mileage: 15000 },
  { id: 'veh-2', customerId: 'cust-1', make: 'Mercedes-Benz', model: 'C-Class', year: 2022, color: 'Obsidian Black', licensePlate: 'KA-01-CD-5678', vin: 'W1KZF8DB5NA012345', mileage: 28000 },
  { id: 'veh-3', customerId: 'cust-2', make: 'Audi', model: 'A4', year: 2024, color: 'Mythos Black', licensePlate: 'DL-02-EF-9012', vin: 'WAUEAAF44KA012345', mileage: 5000 },
  { id: 'veh-4', customerId: 'cust-3', make: 'Toyota', model: 'Fortuner', year: 2023, color: 'Super White', licensePlate: 'GJ-01-GH-3456', vin: 'MHFGB8GS5P0012345', mileage: 32000 },
  { id: 'veh-5', customerId: 'cust-4', make: 'Hyundai', model: 'Creta', year: 2024, color: 'Titan Grey', licensePlate: 'TS-09-IJ-7890', vin: 'MALB381BBKM012345', mileage: 8000 },
  { id: 'veh-6', customerId: 'cust-5', make: 'Tata', model: 'Harrier', year: 2024, color: 'Ash Grey', licensePlate: 'RJ-14-KL-2345', vin: 'MAT667405K0012345', mileage: 12000 },
  { id: 'veh-7', customerId: 'cust-2', make: 'Porsche', model: 'Cayenne', year: 2023, color: 'Carrara White', licensePlate: 'DL-02-MN-6789', vin: 'WP1AA2AY6PDA12345', mileage: 18000 },
];

const allServices: ServiceItem[] = [
  { id: 'srv-1', name: 'Engine Oil Change', description: 'Full synthetic oil change', cost: 3500, laborHours: 1 },
  { id: 'srv-2', name: 'Brake Pad Replacement', description: 'Front and rear brake pads', cost: 8000, laborHours: 2 },
  { id: 'srv-3', name: 'AC Service', description: 'Full AC system check and gas refill', cost: 4500, laborHours: 1.5 },
  { id: 'srv-4', name: 'Wheel Alignment', description: '4-wheel alignment and balancing', cost: 2500, laborHours: 1 },
  { id: 'srv-5', name: 'Full Body Detailing', description: 'Interior and exterior detailing', cost: 12000, laborHours: 6 },
  { id: 'srv-6', name: 'Suspension Check', description: 'Complete suspension inspection', cost: 5000, laborHours: 2 },
  { id: 'srv-7', name: 'Transmission Service', description: 'Transmission fluid change and inspection', cost: 7500, laborHours: 3 },
  { id: 'srv-8', name: 'Battery Replacement', description: 'New battery installation and testing', cost: 6000, laborHours: 0.5 },
];

const allParts: PartItem[] = [
  { id: 'prt-1', name: 'Engine Oil Filter', partNumber: 'OF-2024-A', quantity: 1, unitCost: 800, totalCost: 800 },
  { id: 'prt-2', name: 'Brake Pads (Front)', partNumber: 'BP-FRT-001', quantity: 2, unitCost: 3500, totalCost: 7000 },
  { id: 'prt-3', name: 'AC Compressor Belt', partNumber: 'AC-BLT-015', quantity: 1, unitCost: 1200, totalCost: 1200 },
  { id: 'prt-4', name: 'Air Filter', partNumber: 'AF-STD-022', quantity: 1, unitCost: 650, totalCost: 650 },
  { id: 'prt-5', name: 'Spark Plugs', partNumber: 'SP-IRD-004', quantity: 4, unitCost: 450, totalCost: 1800 },
  { id: 'prt-6', name: 'Wiper Blades', partNumber: 'WB-PRE-009', quantity: 2, unitCost: 900, totalCost: 1800 },
];

export const mockJobCards: JobCard[] = [
  {
    id: 'job-1',
    customerId: 'cust-1',
    customerName: 'Rajesh Kumar',
    vehicleId: 'veh-1',
    vehicleName: 'BMW 3 Series (2023)',
    licensePlate: 'KA-01-AB-1234',
    issues: ['Engine making unusual noise during acceleration', 'Oil leak noticed under the car'],
    status: 'in_progress',
    services: [allServices[0], allServices[5]],
    parts: [allParts[0], allParts[3]],
    estimatedCost: 9950,
    actualCost: 0,
    assignees: [
      { name: 'Anil Kumar', role: 'Service Advisor' },
      { name: 'Suresh', role: 'Primary Technician' },
    ],
    notes: 'Customer requests genuine parts only.',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-11T14:30:00Z',
  },
  {
    id: 'job-2',
    customerId: 'cust-2',
    customerName: 'Priya Sharma',
    vehicleId: 'veh-3',
    vehicleName: 'Audi A4 (2024)',
    licensePlate: 'DL-02-EF-9012',
    issues: ['Scheduled 10,000 km service', 'AC not cooling properly'],
    status: 'approved',
    services: [allServices[0], allServices[2], allServices[3]],
    parts: [allParts[0], allParts[2], allParts[3]],
    estimatedCost: 13150,
    actualCost: 0,
    assignees: [
      { name: 'Deepika', role: 'Service Advisor' },
      { name: 'Ramesh', role: 'Primary Technician' },
    ],
    notes: '',
    createdAt: '2026-04-11T11:00:00Z',
    updatedAt: '2026-04-11T13:00:00Z',
    quoteToken: 'qt-mock-priya-001',
    quoteStatus: 'accepted',
    quoteSentAt: '2026-04-11T11:30:00Z',
    quoteRespondedAt: '2026-04-11T13:00:00Z',
  },
  {
    id: 'job-3',
    customerId: 'cust-3',
    customerName: 'Amit Patel',
    vehicleId: 'veh-4',
    vehicleName: 'Toyota Fortuner (2023)',
    licensePlate: 'GJ-01-GH-3456',
    issues: ['Brakes squeaking', 'Needs full inspection before long trip'],
    status: 'completed',
    services: [allServices[1], allServices[3], allServices[5]],
    parts: [allParts[1], allParts[5]],
    estimatedCost: 24300,
    actualCost: 23800,
    assignees: [
      { name: 'Anil Kumar', role: 'Service Advisor' },
      { name: 'Suresh', role: 'Primary Technician' },
    ],
    notes: 'Vehicle ready for pickup.',
    createdAt: '2026-04-08T08:00:00Z',
    updatedAt: '2026-04-10T17:00:00Z',
  },
  {
    id: 'job-4',
    customerId: 'cust-4',
    customerName: 'Sneha Reddy',
    vehicleId: 'veh-5',
    vehicleName: 'Hyundai Creta (2024)',
    licensePlate: 'TS-09-IJ-7890',
    issues: ['Battery draining overnight', 'Needs electrical system check'],
    status: 'pending',
    services: [allServices[7]],
    parts: [allParts[4]],
    estimatedCost: 7800,
    actualCost: 0,
    assignees: [],
    notes: 'Customer to drop off vehicle tomorrow.',
    createdAt: '2026-04-12T16:00:00Z',
    updatedAt: '2026-04-12T16:00:00Z',
  },
  {
    id: 'job-5',
    customerId: 'cust-5',
    customerName: 'Vikram Singh',
    vehicleId: 'veh-6',
    vehicleName: 'Tata Harrier (2024)',
    licensePlate: 'RJ-14-KL-2345',
    issues: ['Full body detailing requested', 'Interior cleaning requested'],
    status: 'in_progress',
    services: [allServices[4]],
    parts: [],
    estimatedCost: 12000,
    actualCost: 0,
    assignees: [
      { name: 'Kavya', role: 'Service Advisor' },
      { name: 'Detailing Team', role: 'Primary Technician' },
    ],
    notes: 'Premium ceramic coating requested as add-on.',
    createdAt: '2026-04-12T10:00:00Z',
    updatedAt: '2026-04-13T09:00:00Z',
  },
  {
    id: 'job-6',
    customerId: 'cust-1',
    customerName: 'Rajesh Kumar',
    vehicleId: 'veh-2',
    vehicleName: 'Mercedes-Benz C-Class (2022)',
    licensePlate: 'KA-01-CD-5678',
    issues: ['Transmission jerky during gear shifts'],
    status: 'pending',
    services: [allServices[6]],
    parts: [],
    estimatedCost: 7500,
    actualCost: 0,
    assignees: [],
    notes: '',
    createdAt: '2026-04-13T08:00:00Z',
    updatedAt: '2026-04-13T08:00:00Z',
  },
];

export const mockBills: Bill[] = [
  {
    id: 'bill-1',
    jobCardId: 'job-3',
    customerId: 'cust-3',
    customerName: 'Amit Patel',
    vehicleName: 'Toyota Fortuner (2023)',
    licensePlate: 'GJ-01-GH-3456',
    services: [allServices[1], allServices[3], allServices[5]],
    parts: [allParts[1], allParts[5]],
    servicesCost: 15500,
    partsCost: 8800,
    subtotal: 24300,
    taxRate: 18,
    taxAmount: 4374,
    total: 28674,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2026-04-10T17:00:00Z',
    paidAt: '2026-04-10T17:30:00Z',
    paymentToken: 'pay-mock-amit-001',
    paymentLinkStatus: 'paid',
    paymentLinkSentAt: '2026-04-10T17:05:00Z',
    reviewToken: 'rev-mock-amit-001',
    reviewStatus: 'submitted',
    reviewSentAt: '2026-04-10T17:35:00Z',
    reviewRating: 5,
    reviewComment: 'Excellent service! Very professional team.',
    reviewSubmittedAt: '2026-04-10T18:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalJobs: 6,
  pendingJobs: 2,
  inProgressJobs: 2,
  completedJobs: 2,
  totalRevenue: 28674,
  monthlyRevenue: 28674,
  totalCustomers: 5,
  recentJobs: mockJobCards.slice(0, 5),
};

export const mockInventory: InventoryItem[] = [
  { id: 'inv-1', name: 'Engine Oil (5W-30)', partNumber: 'EO-5W30-SYN', category: 'Fluids', quantity: 45, unitCost: 1200, reorderLevel: 10, supplier: 'Castrol India' },
  { id: 'inv-2', name: 'Brake Pads (Universal)', partNumber: 'BP-UNI-001', category: 'Brakes', quantity: 24, unitCost: 3500, reorderLevel: 5, supplier: 'Brembo' },
  { id: 'inv-3', name: 'Air Filter (Standard)', partNumber: 'AF-STD-022', category: 'Filters', quantity: 30, unitCost: 650, reorderLevel: 8, supplier: 'Mann Filter' },
  { id: 'inv-4', name: 'Spark Plugs (Iridium)', partNumber: 'SP-IRD-004', category: 'Ignition', quantity: 60, unitCost: 450, reorderLevel: 15, supplier: 'NGK' },
  { id: 'inv-5', name: 'AC Refrigerant (R134a)', partNumber: 'AC-R134A-CAN', category: 'AC', quantity: 18, unitCost: 800, reorderLevel: 5, supplier: 'Honeywell' },
  { id: 'inv-6', name: 'Transmission Fluid', partNumber: 'TF-ATF-PRO', category: 'Fluids', quantity: 12, unitCost: 2200, reorderLevel: 4, supplier: 'Shell India' },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    jobCardId: 'job-2',
    customerId: 'cust-2',
    customerName: 'Priya Sharma',
    channel: 'whatsapp',
    status: 'accepted',
    quoteToken: 'qt-mock-priya-001',
    message: 'Hello Priya Sharma,\n\nYour vehicle Audi A4 (2024) (DL-02-EF-9012) has been inspected at Car Affair.\n\nEstimated Cost: ₹13,150\n\nView & approve your quote:\nhttp://localhost:3000/quote/qt-mock-priya-001',
    sentAt: '2026-04-11T11:30:00Z',
    deliveredAt: '2026-04-11T11:31:00Z',
    openedAt: '2026-04-11T12:45:00Z',
    respondedAt: '2026-04-11T13:00:00Z',
  },
  {
    id: 'notif-2',
    jobCardId: 'job-2',
    customerId: 'cust-2',
    customerName: 'Priya Sharma',
    channel: 'email',
    status: 'accepted',
    quoteToken: 'qt-mock-priya-001',
    message: 'Dear Priya Sharma,\n\nWe have completed the inspection of your vehicle Audi A4 (2024) (DL-02-EF-9012) at Car Affair.\n\nEstimated Cost: ₹13,150\n\nPlease review and approve your quote.',
    sentAt: '2026-04-11T11:30:00Z',
    deliveredAt: '2026-04-11T11:30:30Z',
    openedAt: '2026-04-11T12:50:00Z',
    respondedAt: '2026-04-11T13:00:00Z',
  },
];

export const availableServices = allServices;
export const availableParts = allParts;
